version: '3'

services:
  janitor-bot:
    container_name: permission-bot
    build:
      dockerfile: Dockerfile
      args:
        - build=1
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - mariadb

networks:
  mariadb:
    name: MariaDB
    external: true